{
 "title": "SYSTEM",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "agg", "query": "1m" }
  ]
 },
 "panels": [
  {
   "title": "NGINX",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"nginx\" and r._field == \"requests\")\n  |> aggregateWindow(every: ${agg}, fn: mean)\n  |> difference(nonNegative: true)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r._measurement == \"cpu\" \n    and (\n      r._field == \"usage_system\"\n      or r._field == \"usage_user\"\n      or r._field == \"usage_iowait\"\n    )\n  )\n  |> filter(fn: (r) => r._field != \"usage_idle\")\n  |> aggregateWindow(every: ${agg}, fn: mean)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    }
   ]
  },
  {
   "title": "MEM",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"mem\" and r._field == \"used_percent\")\n  |> aggregateWindow(every: ${agg}, fn: mean)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    }
   ]
  },
  {
   "title": "DISK I/O",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n  \tr._measurement == \"diskio\" \n  \tand (r._field == \"read_bytes\" or r._field == \"write_bytes\")\n    and r.name == \"sda\"\n  )\n  |> aggregateWindow(every: ${agg}, fn: mean)\n  |> difference(nonNegative: true)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\n  |> map(fn: (r) => (\n\t   { \n         r with \n         _value: if r._field == \"write_bytes\" then -1.0 * r._value else r._value\n       }\n     )\n   )"
    }
   ]
  },
  {
   "title": "DISK",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n  \tr._measurement == \"disk\" \n    and r._field == \"used_percent\"\n    and r.path == \"/\"\n  )\n  |> aggregateWindow(every: ${agg}, fn: mean)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\n"
    }
   ]
  },
  {
   "title": "NET I/O",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n  \tr._measurement == \"net\" \n  \tand (r._field == \"bytes_recv\" or r._field == \"bytes_sent\")\n  )\n  |> aggregateWindow(every: ${agg}, fn: mean)\n  |> difference(nonNegative: true)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\n  |> map(fn: (r) => (\n\t   { \n         r with \n         _value: if r._field == \"bytes_sent\" then -1.0 * r._value else r._value\n       }\n     )\n   )"
    }
   ]
  },
  {
   "title": "KERNEL",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r._measurement == \"kernel\" \n    and (r._field == \"context_switches\" or r._field == \"interrupts\")\n  )\n  |> aggregateWindow(every: ${agg}, fn: mean)\n  |> difference(nonNegative: true)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    }
   ]
  },
  {
   "title": "SWAP",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"swap\" and r._field == \"used_percent\")\n  |> aggregateWindow(every: ${agg}, fn: mean)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    }
   ]
  },
  {
   "title": "PROCESSES",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"processes\")\n  |> aggregateWindow(every: ${agg}, fn: mean)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    }
   ]
  },
  {
   "title": "POSTGRES",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r._measurement == \"postgresql\" \n    and r.db =~ /_production/\n    and r._field != \"datname\"\n    and (r._field == \"conflicts\" or r._field == \"xact_rollback\" or r._field == \"deadlocks\")\n  )\n  |> aggregateWindow(every: ${agg}, fn: mean)\n  |> difference(nonNegative: true)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\n\n"
    }
   ]
  }
 ]
}