# frozen_string_literal: true

source 'https://rubygems.org'

gem 'addressable'
gem 'aws-sdk-s3'
gem 'bcrypt_pbkdf'
gem 'bcrypt'
gem 'bencode'
gem 'chronic_duration'
gem 'cronex'
gem 'ed25519'
gem 'filesize'
gem 'json'
gem 'jwt'
gem 'net-ssh', '~> 7.0.0.beta1'
gem 'parseconfig'
gem 'pg'
gem 'public_suffix'
gem 'puma'
gem 'rails'
gem 'redis-rails'
gem 'redis'
gem 'rest-client'
gem 'rexml'
gem 'sass-rails'
gem 'sendgrid-actionmailer'
gem 'sentry-rails'
gem 'sidekiq-failures'
gem 'sidekiq-scheduler'
gem 'sidekiq-status'
gem 'sidekiq'
gem 'webpacker', '~> 6.0.0.beta.2'
gem 'xmlrpc'
gem 'yaml'
gem "ferrum"
gem "sentry-ruby"

group :development, :test do
  gem 'annotate'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'foreman'
  gem 'listen'
  gem 'mocha'
  gem 'pry'
  gem 'qprof'
  gem 'rubocop-rails', '2.11.3'
  gem 'rubocop', '1.17.0'
  gem 'webmock'
end
