source 'https://rubygems.org'

gem 'addressable'
gem 'aws-sdk-s3'
gem 'bcrypt'
gem 'bcrypt_pbkdf'
gem 'bencode'
gem 'chronic_duration'
gem 'cronex'
gem 'ed25519'
gem "ferrum"
gem 'filesize'
gem 'jsbundling-rails'
gem 'jwt'
gem 'pg'
gem 'public_suffix'
gem 'puma'
gem 'rails'
gem 'redis'
gem 'redis-rails'
gem 'rexml'
gem 'sass-rails'
gem 'sendgrid-actionmailer'
gem 'sentry-rails'
gem "sentry-ruby"
gem 'sidekiq'
gem 'sidekiq-failures'
gem 'sidekiq-scheduler'
gem 'sidekiq-status'
gem 'xmlrpc'

group :default, :deploy, :development, :test do
  gem 'json'
  gem 'net-ssh', '~> 7.0.0.beta1'
  gem 'open3'
  gem 'parseconfig'
  gem 'pry'
  gem 'rest-client'
  gem 'yaml'
end

group :development, :test do
  gem 'annotate'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'foreman'
  gem 'listen'
  gem 'mocha'
  gem 'qprof'
  gem 'rubocop', '1.17.0'
  gem 'rubocop-rails', '2.11.3'
  gem 'webmock'
end
